[package]
name = "iron-spider"
version = "0.1.0"
authors = ["Parker Given <rgiven@amazon.com>"]
edition = "2018"

[dependencies]
discord = { git = "https://github.com/ArtemGr/discord-rs.git" }
config = "0.9"